### ISSUE TITLE
"max_msg_size" for the snmp session is insufficient

### ISSUE THREAD

**Issue by kirk444** [DarkNinja77/check_snmp_environment.pl#1]
$ ./check_snmp_environment.pl -H <hostname> -C public -T ciscoNEW -v            
Alarm at 15 + 5
SNMP v2c login
Checking Cisco CISCO-ENTITY-SENSOR-MIB env
ERROR: The message size exceeded the buffer maxMsgSize of 1472 : UNKNOWN

I naively increased the size ($session->max_msg_size(5000); right after the session is checked for errors) and that seems to work, but I don't know what the 'correct' solution is for this.

For what it's worth, I was previously using the "0.7cra" version of this from someone else, and it uses the default 1472 as well, and it has no problems, so I think the extra threshold queries bring it over the maximum.

**Comment by DarkNinja77** [comment]
not getting this error in my environment. is your monitoring host and the snmp target in the same ip network and are you using jumbo frames? this might explain the message size problem, but just guessing.
what you did probably is fine.
i'm not a perl expert, just an unskilled hacker.

**Comment by kirk444** [comment]
My monitoring host has jumbo frames, but the snmp target doesn't, that seems likely to be the cause, still.
