### ISSUE TITLE
-bash: ./check_snmp_environment.pl: /usr/bin/perl^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by ste-giraldo** [DarkNinja77/check_snmp_environment.pl#3]
Hi, there's an error in the code, when I try to run I have this output: 
`-bash: ./check_snmp_environment.pl: /usr/bin/perl^M: bad interpreter: No such file or directory`

I fixed with a `# dos2unix check_snmp_environment.pl`
`dos2unix: converting file check_snmp_environment.pl to Unix format...`

Now it works again. Following the fixed code for you.

[check_snmp_environment.pl.txt](https://github.com/DarkNinja77/check_snmp_environment.pl/files/7621194/check_snmp_environment.pl.txt)

**Comment by DarkNinja77** [comment]
not reproducible
